version: "3.5"
services:
  local-notebooks:
    container_name: local-notebooks
    build:
      context: ./jupyter-lab-setup
      dockerfile: Dockerfile
    volumes:
      - ./experiences:/notebooks
      - ./jupyter-lab-setup/settings:/usr/local/share/jupyter/lab/settings
    ports:
      - "8888:8888" 
