version: "3.5"
services:      
  local-notebooks:
    container_name: local-notebooks
    build:
      context: ./development
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "8888:8888" 
