version: "3.5"
services:
  local-notebooks:
    container_name: local-notebooks
    build:
      context: ./jupyter-lab-setup
      dockerfile: Dockerfile.development
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "8888:8888" 
